## This file is a template remove the .template to use the file

libraries:                           # This is called out once within the config.yml file
  Movies (m):                            # These are names of libraries in your Plex
    sync_mode: sync
    # report_path: ../../.data/Plex-Meta-Manager/reports/Movies (m) Report.yml
    report_path: C:\Users\muelm\AppData\Local\Plex Media Server\_kometa_data_\reports\Movies (m) Report.yml
    remove_overlays: false           # Set this to true to remove all overlays
    collection_files:
    - default: basic                 # This is a file within Kometa's defaults folder
    - default: imdb                  # This is a file within Kometa's defaults folder
      # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files:
    - default: ribbon                # This is a file within Kometa's defaults folder
  Movies 4k (m):                            # These are names of libraries in your Plex
    sync_mode: sync
    # report_path: ../../.data/Plex-Meta-Manager/reports/Movies 4k (m) Report.yml
    report_path: C:\Users\muelm\AppData\Local\Plex Media Server\_kometa_data_\reports\Movies 4k (m) Report.yml
    remove_overlays: false           # Set this to true to remove all overlays
    collection_files:
    - default: basic                 # This is a file within Kometa's defaults folder
    - default: imdb                  # This is a file within Kometa's defaults folder
      # see the wiki for how to use local files, folders, URLs, or files from git
    overlays:
      4K:
        plex_search:
          all:
            resolution: 4K
    overlay_files:
    - default: ribbon                # This is a file within Kometa's defaults folder
      # see the wiki for how to use local files, folders, URLs, or files from git
      # see the wiki for how to use local files, folders, URLs, or files from git
  Kids' Movies (m):                            # These are names of libraries in your Plex
    remove_overlays: false           # Set this to true to remove all overlays
    collection_files:
    - default: basic                 # This is a file within Kometa's defaults folder
    - default: imdb                  # This is a file within Kometa's defaults folder
      # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files:
    - default: ribbon                # This is a file within Kometa's defaults folder
      # see the wiki for how to use local files, folders, URLs, or files from git
      # see the wiki for how to use local files, folders, URLs, or files from git
  TV Shows (m):
    remove_overlays: false           # Set this to true to remove all overlays
    collection_files:
    - default: basic                 # This is a file within Kometa's defaults folder
    - default: imdb                  # This is a file within Kometa's defaults folder
      # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files:
    - default: ribbon                # This is a file within Kometa's defaults folder
      # see the wiki for how to use local files, folders, URLs, or files from git
  Kids' TV Shows (m):
    remove_overlays: false           # Set this to true to remove all overlays
    collection_files:
    - default: basic                 # This is a file within Kometa's defaults folder
    - default: imdb                  # This is a file within Kometa's defaults folder
      # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files:
    - default: ribbon                # This is a file within Kometa's defaults folder
      # see the wiki for how to use local files, folders, URLs, or files from git
  # Anime:
  #   collection_files:
  #     - default: basic               # This is a file within Kometa's defaults folder
  #     - default: anilist             # This is a file within Kometa's defaults folder
  #     # see the wiki for how to use local files, folders, URLs, or files from git
  Albums (m):
    # collection_files:
    #   - default: Music\Artists                 # This is a file within Kometa's defaults folder
    #   - default: Music\Albums                  # This is a file within Kometa's defaults folder
      # - default: Music\Year
    # report_path: ../../.data/Plex-Meta-Manager/reports/Music/Albums Report.yml
    report_path: C:\Users\muelm\AppData\Local\Plex Media Server\_kometa_data_\reports\Music\Albums Report.yml
      # - file: config/Music.yml       # This is a local file THAT YOU MIGHT CREATE
playlist_files:
- default: playlist                  # This is a file within Kometa's defaults folder
  template_variables:
    libraries: Movies (m), TV Shows (m)      # list of libraries that you want the Kometa Defaults playlists to look at
  # see the wiki for how to use local files, folders, URLs, or files from git
settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  cache: true
  cache_expiration: 60
  # asset_directory: C:\Users\muelm\AppData\Local\Plex Media Server\_kometa_data_\assets
  asset_directory: $env:LOCALAPPDATA\\Plex Media Server\\_kometa_data_\\assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: true
  show_missing: true
  show_missing_assets: true
  save_report: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  overlay_artwork_filetype: jpg
  overlay_artwork_quality: 75
webhooks:                            # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:
plex:                                # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://127.0.0.1:32400/
  token: u1sgxR-chWpDx4kXW29X
  timeout: 60
  db_cache: 4096
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl:
tmdb:                                # REQUIRED for the script to run
  apikey: 505921ccc353c19f56750ca9224f874d
  language: en
  cache_expiration: 60
  region:
tautulli:                            # Can be individually specified per library as well
  url: http://slobo-vectorpro.slbhm:32500/
  apikey: 0xGve9sV1EopAqsBsyc41SzDu12cqvi_
  # verify_ssl: false
github:
  token: ################################
omdb:
  apikey: 11bc2e53
  cache_expiration: 60
mdblist:
  apikey: r6vn1pmhs11kkv3zcpixdil26
  cache_expiration: 60
# notifiarr:
#   apikey: ####################################
# gotify:
#   url: http://192.168.1.12:80
#   token: ####################################
# anidb:                               # Not required for AniDB builders unless you want mature content
#   username: ######
#   password: ######
# radarr:                              # Can be individually specified per library as well
#   url: http://192.168.1.12:7878
#   token: ################################
#   add_missing: false
#   add_existing: false
#   upgrade_existing: false
#   monitor_existing: false
#   root_folder_path: "S:/Movies"
#   monitor: true
#   availability: announced
#   quality_profile: HD-1080p
#   tag:
#   search: false
#   radarr_path:
#   plex_path:
# sonarr:                              # Can be individually specified per library as well
#   url: http://192.168.1.12:8989
#   token: ################################
#   add_missing: false
#   add_existing: false
#   upgrade_existing: false
#   monitor_existing: false
#   root_folder_path: "S:/TV Shows"
#   monitor: all
#   quality_profile: HD-1080p
#   language_profile: English
#   series_type: standard
#   season_folder: true
#   tag:
#   search: false
#   cutoff_search: false
#   sonarr_path:
#   plex_path:
trakt:
  client_id: 1aec3521e7b29253d4ef83b0fecdfd6ad8955085a212e07491b47a173b71c3f6
  client_secret: ed1592abf47fb17e72ee1d2d6611f9bfaf1c89e6e633da513b5a7a0a14c775a4
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token: 48324c398fd76c863e6ed122bb8ffd89f2f910af5d62f2c07217171983ce8b5d
    token_type: Bearer
    expires_in: 7889238
    refresh_token: 26439210b96aebe2b794e6c22c3949185147d8433aaf8fd26ed07133c3951a62
    scope: public
    created_at: 1744637478
