IMDb Popular:
  Movies Missing (TMDb IDs):
    280180: 'Beverly Hills Cop: Axel F (2024)'
    987686: A Family Affair (2024)
    762441: A Quiet Place: Day One (2024)
    801688: Kalki 2898 - AD (2024)
    1022789: Inside Out 2 (2024)
    932086: 'Horizon: An American Saga - Chapter 1 (2024)'
    786892: 'Furiosa: A Mad Max Saga (2024)'
    1226578: Longlegs (2024)
    1023922: MaXXXine (2024)
    533535: Deadpool & Wolverine (2024)
    1029955: Kinds of Kindness (2024)
    519182: Despicable Me 4 (2024)
    90: Beverly Hills Cop (1984)
    1008409: The Bikeriders (2024)
    602: Independence Day (1996)
    558449: Gladiator II (2024)
    1086747: The Watchers (2024)
    974635: Hit Man (2024)
    1214509: In a Violent Nature (2024)
    150540: Inside Out (2015)
    1032823: Trap (2024)
    573435: 'Bad Boys: Ride or Die (2024)'
    866398: The Beekeeper (2024)
    760104: X (2022)
    704673: Trigger Warning (2024)
    447332: A Quiet Place (2018)
    929590: Civil War (2024)
    872585: Oppenheimer (2023)
    718821: Twisters (2024)
    823464: 'Godzilla x Kong: The New Empire (2024)'
    799583: The Ministry of Ungentlemanly Warfare (2024)
    1062215: Afraid (2024)
    693134: 'Dune: Part Two (2024)'
    76341: 'Mad Max: Fury Road (2015)'
    746036: The Fall Guy (2024)
    1087822: 'Hellboy: The Crooked Man (2024)'
    1019411: Space Cadet (2024)
    1072790: Anyone But You (2023)
    1114738: Boneyard (2024)
    949423: Pearl (2022)
    664: Twister (1996)
    956842: Fly Me to the Moon (2024)
    426063: Nosferatu (2024)
    306: Beverly Hills Cop III (1994)
    792307: Poor Things (2023)
    520763: A Quiet Place Part II (2021)
    653346: Kingdom of the Planet of the Apes (2024)
    96: Beverly Hills Cop II (1987)
    940139: Here (2024)
    845781: Red One (2024)
    1160018: Kill (2024)
    967847: 'Ghostbusters: Frozen Empire (2024)'
    937287: Challengers (2024)
    578: Jaws (1975)
    1001311: Under Paris (2024)
    98: Gladiator (2000)
    9437: Kiss the Girls (1997)
    850165: The Iron Claw (2023)
    560016: Monkey Man (2024)
    1242526: 'Sound of Hope: The Story of Possum Trot (2024)'
    1061474: Superman (2025)
    634492: Madame Web (2024)
    940721: Godzilla Minus One (2023)
    278: The Shawshank Redemption (1994)
    1051891: Thelma (2024)
    843527: The Idea of You (2024)
    938614: Late Night with the Devil (2024)
    438631: Dune (2021)
    1187058: Munjya (2024)
    11528: The Sandlot (1993)
    1058617: Fancy Dance (2024)
    1111873: Abigail (2024)
    508883: The Boy and the Heron (2023)
    361743: 'Top Gun: Maverick (2022)'
    68735: Warcraft (2016)
    437342: The First Omen (2024)
    11092: Presumed Innocent (1990)
    858017: I Saw the TV Glow (2024)
    945961: 'Alien: Romulus (2024)'
    157336: Interstellar (2014)
    948549: Love Lies Bleeding (2024)
    597: Titanic (1997)
    359410: Road House (2024)
    238: The Godfather (1972)
    1079091: It Ends with Us (2024)
    1171099: Maharaj (2024)
    726209: Leave the World Behind (2023)
    530385: Midsommar (2019)
    917496: Beetlejuice Beetlejuice (2024)
    1216221: 'Demon Slayer: Kimetsu no Yaiba -To the Hashira Training- (2024)'
    974262: 'Descendants: The Rise of Red (2024)'
    2024: The Patriot (2000)
    930564: Saltburn (2023)
    105: Back to the Future (1985)
    293660: Deadpool (2016)
    155: The Dark Knight (2008)
    671: Harry Potter and the Philosopher's Stone (2001)
IMDb Top 250:
  Movies Missing (TMDb IDs):
    278: The Shawshank Redemption (1994)
    238: The Godfather (1972)
    155: The Dark Knight (2008)
    240: The Godfather Part II (1974)
    389: 12 Angry Men (1957)
    424: Schindler's List (1993)
    122: 'The Lord of the Rings: The Return of the King (2003)'
    680: Pulp Fiction (1994)
    120: 'The Lord of the Rings: The Fellowship of the Ring (2001)'
    429: The Good, the Bad and the Ugly (1966)
    13: Forrest Gump (1994)
    121: 'The Lord of the Rings: The Two Towers (2002)'
    550: Fight Club (1999)
    27205: Inception (2010)
    1891: The Empire Strikes Back (1980)
    603: The Matrix (1999)
    769: GoodFellas (1990)
    510: One Flew Over the Cuckoo's Nest (1975)
    807: Se7en (1995)
    157336: Interstellar (2014)
    1585: It's a Wonderful Life (1946)
    346: Seven Samurai (1954)
    274: The Silence of the Lambs (1991)
    857: Saving Private Ryan (1998)
    598: City of God (2002)
    637: Life Is Beautiful (1997)
    497: The Green Mile (1999)
    280: 'Terminator 2: Judgment Day (1991)'
    11: Star Wars (1977)
    105: Back to the Future (1985)
    129: Spirited Away (2001)
    423: The Pianist (2002)
    496243: Parasite (2019)
    539: Psycho (1960)
    693134: 'Dune: Part Two (2024)'
    98: Gladiator (2000)
    8587: The Lion King (1994)
    1422: The Departed (2006)
    101: 'Léon: The Professional (1994)'
    73: American History X (1998)
    244786: Whiplash (2014)
    1124: The Prestige (2006)
    12477: Grave of the Fireflies (1988)
    14537: Harakiri (1962)
    629: The Usual Suspects (1995)
    289: Casablanca (1943)
    77338: The Intouchables (2011)
    11216: Cinema Paradiso (1988)
    3082: Modern Times (1936)
    567: Rear Window (1954)
    335: Once Upon a Time in the West (1968)
    348: Alien (1979)
    901: City Lights (1931)
    68718: Django Unchained (2012)
    28: Apocalypse Now (1979)
    77: Memento (2000)
    10681: WALL·E (2008)
    85: Raiders of the Lost Ark (1981)
    1163258: 12th Fail (2023)
    582: The Lives of Others (2006)
    599: Sunset Boulevard (1950)
    299536: 'Avengers: Infinity War (2018)'
    975: Paths of Glory (1957)
    324857: 'Spider-Man: Into the Spider-Verse (2018)'
    37257: Witness for the Prosecution (1957)
    694: The Shining (1980)
    914: The Great Dictator (1940)
    679: Aliens (1986)
    16869: Inglourious Basterds (2009)
    49026: The Dark Knight Rises (2012)
    354912: Coco (2017)
    935: 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)'
    279: Amadeus (1984)
    670: Oldboy (2003)
    14: American Beauty (1999)
    299534: 'Avengers: Endgame (2019)'
    387: Das Boot (1981)
    197: Braveheart (1995)
    489: Good Will Hunting (1997)
    128: Princess Mononoke (1997)
    475557: Joker (2019)
    372058: Your Name. (2016)
    12493: High and Low (1963)
    20453: 3 Idiots (2009)
    311: Once Upon a Time in America (1984)
    872: Singin' in the Rain (1952)
    517814: Capernaum (2018)
    25237: Come and See (1985)
    641: Requiem for a Dream (2000)
    1892: Return of the Jedi (1983)
    38: Eternal Sunshine of the Spotless Mind (2004)
    103663: The Hunt (2012)
    62: '2001: A Space Odyssey (1968)'
    500: Reservoir Dogs (1992)
    3782: Ikiru (1952)
    947: Lawrence of Arabia (1962)
    872585: Oppenheimer (2023)
    284: The Apartment (1960)
    46738: Incendies (2010)
    213: North by Northwest (1959)
    15: Citizen Kane (1941)
    111: Scarface (1983)
    996: Double Indemnity (1944)
    832: M (1931)
    426: Vertigo (1958)
    600: Full Metal Jacket (1987)
    194: Amélie (2001)
    949: Heat (1995)
    14160: Up (2009)
    185: A Clockwork Orange (1971)
    595: To Kill a Mockingbird (1962)
    60243: A Separation (2011)
    9277: The Sting (1973)
    562: Die Hard (1988)
    89: Indiana Jones and the Last Crusade (1989)
    7508: Like Stars on Earth (2007)
    19: Metropolis (1927)
    107: Snatch (2000)
    530915: 1917 (2019)
    2118: L.A. Confidential (1997)
    5156: Bicycle Thieves (1948)
    556574: Hamilton (2020)
    103: Taxi Driver (1976)
    613: Downfall (2004)
    360814: Dangal (2016)
    272: Batman Begins (2005)
    938: For a Few Dollars More (1965)
    106646: The Wolf of Wall Street (2013)
    239: Some Like It Hot (1959)
    490132: Green Book (2018)
    10098: The Kid (1921)
    600354: The Father (2020)
    821: Judgment at Nuremberg (1961)
    37165: The Truman Show (1998)
    705: All About Eve (1950)
    11324: Shutter Island (2010)
    361743: 'Top Gun: Maverick (2022)'
    7345: There Will Be Blood (2007)
    524: Casino (1995)
    329: Jurassic Park (1993)
    11645: Ran (1985)
    745: The Sixth Sense (1999)
    1417: Pan's Labyrinth (2006)
    33: Unforgiven (1992)
    6977: No Country for Old Men (2007)
    453: A Beautiful Mind (2001)
    1091: The Thing (1982)
    24: 'Kill Bill: Vol. 1 (2003)'
    3090: The Treasure of the Sierra Madre (1948)
    11878: Yojimbo (1961)
    762: Monty Python and the Holy Grail (1975)
    5925: The Great Escape (1963)
    146233: Prisoners (2013)
    4935: Howl's Moving Castle (2004)
    548: Rashomon (1950)
    1955: The Elephant Man (1980)
    521: Dial M for Murder (1954)
    829: Chinatown (1974)
    770: Gone with the Wind (1939)
    100: Lock, Stock and Two Smoking Barrels (1998)
    752: V for Vendetta (2006)
    25376: The Secret in Their Eyes (2009)
    150540: Inside Out (2015)
    1578: Raging Bull (1980)
    359940: Three Billboards Outside Ebbing, Missouri (2017)
    627: Trainspotting (1996)
    826: The Bridge on the River Kwai (1957)
    508965: Klaus (2019)
    275: Fargo (1996)
    640: Catch Me If You Can (2002)
    634649: 'Spider-Man: No Way Home (2021)'
    59440: Warrior (2011)
    13223: Gran Torino (2008)
    12445: 'Harry Potter and the Deathly Hallows: Part 2 (2011)'
    70: Million Dollar Baby (2004)
    8392: My Neighbor Totoro (1988)
    21334: Children of Heaven (1997)
    76203: 12 Years a Slave (2013)
    665: Ben-Hur (1959)
    78: Blade Runner (1982)
    76: Before Sunrise (1995)
    76341: 'Mad Max: Fury Road (2015)'
    3175: Barry Lyndon (1975)
    120467: The Grand Budapest Hotel (2014)
    210577: Gone Girl (2014)
    324786: Hacksaw Ridge (2016)
    207: Dead Poets Society (1989)
    11423: Memories of Murder (2003)
    962: The Gold Rush (1925)
    7984: In the Name of the Father (1993)
    265195: Wild Tales (2014)
    11778: The Deer Hunter (1978)
    961: The General (1926)
    992: Sherlock Jr. (1924)
    654: On the Waterfront (1954)
    578: Jaws (1975)
    10191: How to Train Your Dragon (2010)
    24238: Mary and Max (2009)
    2062: Ratatouille (2007)
    1092: The Third Man (1949)
    204: The Wages of Fear (1953)
    614: Wild Strawberries (1957)
    3083: Mr. Smith Goes to Washington (1939)
    359724: Ford v Ferrari (2019)
    18148: Tokyo Story (1953)
    115: The Big Lebowski (1998)
    1366: Rocky (1976)
    490: The Seventh Seal (1957)
    264644: Room (2015)
    263115: Logan (2017)
    314365: Spotlight (2015)
    205: Hotel Rwanda (2004)
    218: The Terminator (1984)
    792: Platoon (1986)
    406: La Haine (1995)
    80: Before Sunset (2004)
    780: The Passion of Joan of Arc (1928)
    22: 'Pirates of the Caribbean: The Curse of the Black Pearl (2003)'
    887: The Best Years of Our Lives (1946)
    855400: Jai Bhim (2021)
    9552: The Exorcist (1973)
    96721: Rush (2013)
    10774: Network (1976)
    630: The Wizard of Oz (1939)
    235: Stand by Me (1986)
    28178: "Hachi: A Dog's Tale (2009)"
    15121: The Sound of Music (1965)
    290098: The Handmaiden (2016)
    13393: My Father and My Son (2005)
    5915: Into the Wild (2007)
    198: To Be or Not to Be (1942)
    17295: The Battle of Algiers (1966)
    596: The Grapes of Wrath (1940)
    137: Groundhog Day (1993)
    55: Amores Perros (2000)
    10386: The Iron Giant (1999)
    223: Rebecca (1940)
    903: Cool Hand Luke (1967)
    50014: The Help (2011)
    3078: It Happened One Night (1934)
    812: Aladdin (1992)
    635302: 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train (2020)'
    581: Dances with Wolves (1990)
    655: Paris, Texas (1984)
IMDb Lowest Rated:
  Movies Missing (TMDb IDs):
    13805: Disaster Movie (2008)
    22293: 'Manos: The Hands of Fate (1966)'
    40016: 'Birdemic: Shock and Terror (2010)'
    31117: 'Superbabies: Baby Geniuses 2 (2004)'
    295884: Saving Christmas (2014)
    63315: The Hottie & The Nottie (2008)
    11059: House of the Dead (2003)
    10214: Son of the Mask (2005)
    679844: Radhe (2021)
    9760: Epic Movie (2007)
    19213: Pledge This! (2006)
    5491: Battlefield Earth (2000)
    12142: Alone in the Dark (2005)
    14164: Dragonball Evolution (2009)
    496320: Race 3 (2018)
    116977: Foodfight! (2012)
    19157: Going Overboard (1989)
    31246: From Justin to Kelly (2003)
    31279: Turks in Space (2006)
    7278: Meet the Spartans (2008)
    8046: Gigli (2003)
    10073: Date Movie (2006)
    9596: Daniel, the Wizard (2004)
    536869: Cats (2019)
    22345: Baby Geniuses (1999)
    10696: Glitter (2001)
    681887: Cosmic Sin (2021)
    94365: The Human Centipede 3 (Final Sequence) (2015)
    580: 'Jaws: The Revenge (1987)'
    717728: 'Jeepers Creepers: Reborn (2022)'
    829557: '365 Days: This Day (2022)'
    26914: Troll 2 (1990)
    168705: BloodRayne (2005)
    876671: The Cost of Deception (2021)
    31245: Hobgoblins (1988)
    980078: 'Winnie the Pooh: Blood and Honey (2023)'
    734253: Adipurush (2023)
    218043: Left Behind (2014)
    495339: 'Enes Batur: Imagination or Reality? (2018)'
    664413: 365 Days (2020)
    15581: Who's Your Caddy? (2007)
    71880: Jack and Jill (2011)
    11535: Rollerball (2002)
    32307: Santa Claus Conquers the Martians (1964)
    439015: Slender Man (2018)
    314: Catwoman (2004)
    11511: Kazaam (1996)
    503129: Student of the Year 2 (2019)
    651571: Breach (2020)
    8854: Steel (1997)
    603673: Laxmii (2020)
    485774: The Open House (2018)
    40264: Vampires Suck (2010)
    225703: The Starving Games (2013)
    378236: The Emoji Movie (2017)
    46040: Tees Maar Khan (2010)
    10152: 'Dumb and Dumberer: When Harry Met Lloyd (2003)'
    4258: Scary Movie 5 (2013)
    16780: The Return of the Texas Chainsaw Massacre (1995)
    250551: Gunday (2014)
    17473: The Room (2003)
    13908: The Master of Disguise (2002)
    415861: Smolensk (2016)
    14144: Daddy Day Camp (2007)
    11546: 'Police Academy: Mission to Moscow (1994)'
    14123: Bratz (2007)
    7916: Far Cry (2008)
    5227: Hercules in New York (1970)
    594669: Baaghi 3 (2020)
    9544: FearDotCom (2002)
    9823: 'Mortal Kombat: Annihilation (1997)'
    11867: Barb Wire (1996)
    32302: '3 Ninjas: High Noon at Mega Mountain (1998)'
    351819: Fifty Shades of Black (2016)
    415: Batman & Robin (1997)
    13995: Captain America (1990)
    56288: 'Spy Kids: All the Time in the World (2011)'
    27793: The NeverEnding Story III (1994)
    551808: Black Christmas (2019)
    17692: Jaws 3-D (1983)
    11411: 'Superman IV: The Quest for Peace (1987)'
    19139: 'Goal III: Taking on the World (2009)'
    11849: Dungeons & Dragons (2000)
    10253: 'Dragon Wars: D-War (2007)'
    20196: Mac and Me (1988)
    67911: 'Bucky Larson: Born to Be a Star (2011)'
    791: The Fog (2005)
    9708: The Wicker Man (2006)
    6116: Spice World (1997)
    787163: Liger (2022)
    71668: Piranha 3DD (2012)
    5857: I Know Who Killed Me (2007)
    244688: The Hungover Games (2014)
    14199: The Adventures of Sharkboy and Lavagirl (2005)
    12177: The Love Guru (2008)
    2312: 'In the Name of the King: A Dungeon Siege Tale (2007)'
    9320: The Avengers (1998)
    74997: The Human Centipede 2 (Full Sequence) (2011)
    889: The Flintstones in Viva Rock Vegas (2000)
    17130: Crossroads (2002)
