IMDb Popular:
  Movies Missing (TMDb IDs):
    617126: 'The Fantastic Four: First Steps (2025)'
    1234821: Jurassic World Rebirth (2025)
    1084199: Companion (2025)
    426063: Nosferatu (2024)
    996821: You're Cordially Invited (2025)
    549509: The Brutalist (2024)
    933260: The Substance (2024)
    1097549: Babygirl (2024)
    1000837: I'm Still Here (2024)
    974950: Emilia Pérez (2024)
    1212142: Kinda Pregnant (2025)
    558449: Gladiator II (2024)
    1064213: Anora (2024)
    1120911: Saturday Night (2024)
    710295: Wolf Man (2025)
    661539: A Complete Unknown (2024)
    974576: Conclave (2024)
    822119: 'Captain America: Brave New World (2025)'
    840705: Blink Twice (2024)
    774370: Dog Man (2025)
    137: Groundhog Day (1993)
    1013850: A Real Pain (2024)
    1126166: Flight Risk (2025)
    1071585: M3GAN 2.0 (2025)
    993710: Back in Action (2025)
    574475: Final Destination Bloodlines (2025)
    604685: 'Den of Thieves 2: Pantera (2025)'
    1226406: Love Hurts (2025)
    1195430: Deva (2025)
    857598: Pushpa 2 - The Rule (2024)
    1302916: Heart Eyes (2025)
    1211472: September 5 (2024)
    1082195: The Order (2024)
    593643: The Menu (2022)
    1079091: It Ends With Us (2024)
    1138194: Heretic (2024)
    98: Gladiator (2000)
    157336: Interstellar (2014)
    1124620: The Monkey (2025)
    762509: 'Mufasa: The Lion King (2024)'
    940139: Here (2024)
    1100099: We Live in Time (2024)
    823219: Flow (2024)
    1114894: 'Star Trek: Section 31 (2025)'
    1140535: Presence (2025)
    1217690: Homestead (2024)
    786892: 'Furiosa: A Mad Max Saga (2024)'
    1368337: The Odyssey (2026)
    1106739: 'Juror #2 (2024)'
    1272149: 'Bridget Jones: Mad About the Boy (2025)'
    945961: 'Alien: Romulus (2024)'
    693134: 'Dune: Part Two (2024)'
    1182047: The Apprentice (2024)
    278: The Shawshank Redemption (1994)
    1109255: Parthenope (2024)
    950396: The Gorge (2025)
    539972: Kraven the Hunter (2024)
    449443: Den of Thieves (2018)
    1061474: Superman (2025)
    238: The Godfather (1972)
    533535: Deadpool & Wolverine (2024)
    696506: Mickey 17 (2025)
    989662: A Different Man (2024)
    1226578: Longlegs (2024)
    1059128: Queer (2024)
    9340: The Goonies (1985)
    1232827: The Girl with the Needle (2024)
    1028196: Nickel Boys (2024)
    728949: Nightbitch (2024)
    1084736: The Count of Monte Cristo (2024)
    929590: Civil War (2024)
    1280672: One of Them Days (2025)
    912649: 'Venom: The Last Dance (2024)'
    1005331: Carry-On (2024)
    496243: Parasite (2019)
    283378: Fallen (2016)
    807: Se7en (1995)
    1093237: Hurry Up Tomorrow (2025)
    636279: 'Bogotá: City of the Lost (2024)'
    872585: Oppenheimer (2023)
    1278827: The Wedding Banquet (2025)
    466272: Once Upon a Time... in Hollywood (2019)
    1233413: Sinners (2025)
    1300607: Lucca's World (2025)
    27205: Inception (2010)
    980477: Ne Zha 2 (2025)
    1018: Mulholland Drive (2001)
    1087192: How to Train Your Dragon (2025)
    792307: Poor Things (2023)
    1245347: Twinless (2025)
    507241: The Killer's Game (2024)
    1061699: The Six Triple Eight (2024)
    1088096: Goodrich (2024)
    680: Pulp Fiction (1994)
    1278263: The Seed of the Sacred Fig (2024)
IMDb Top 250:
  Movies Missing (TMDb IDs):
    278: The Shawshank Redemption (1994)
    238: The Godfather (1972)
    155: The Dark Knight (2008)
    240: The Godfather Part II (1974)
    389: 12 Angry Men (1957)
    122: 'The Lord of the Rings: The Return of the King (2003)'
    424: Schindler's List (1993)
    680: Pulp Fiction (1994)
    120: 'The Lord of the Rings: The Fellowship of the Ring (2001)'
    429: The Good, the Bad and the Ugly (1966)
    13: Forrest Gump (1994)
    121: 'The Lord of the Rings: The Two Towers (2002)'
    550: Fight Club (1999)
    27205: Inception (2010)
    1891: The Empire Strikes Back (1980)
    603: The Matrix (1999)
    769: GoodFellas (1990)
    510: One Flew Over the Cuckoo's Nest (1975)
    157336: Interstellar (2014)
    807: Se7en (1995)
    1585: It's a Wonderful Life (1946)
    346: Seven Samurai (1954)
    274: The Silence of the Lambs (1991)
    857: Saving Private Ryan (1998)
    598: City of God (2002)
    497: The Green Mile (1999)
    637: Life Is Beautiful (1997)
    280: 'Terminator 2: Judgment Day (1991)'
    11: Star Wars (1977)
    105: Back to the Future (1985)
    129: Spirited Away (2001)
    423: The Pianist (2002)
    98: Gladiator (2000)
    496243: Parasite (2019)
    539: Psycho (1960)
    8587: The Lion King (1994)
    12477: Grave of the Fireflies (1988)
    1422: The Departed (2006)
    244786: Whiplash (2014)
    14537: Harakiri (1962)
    73: American History X (1998)
    1124: The Prestige (2006)
    101: 'Léon: The Professional (1994)'
    289: Casablanca (1943)
    629: The Usual Suspects (1995)
    77338: The Intouchables (2011)
    11216: Cinema Paradiso (1988)
    3082: Modern Times (1936)
    348: Alien (1979)
    567: Rear Window (1954)
    335: Once Upon a Time in the West (1968)
    68718: Django Unchained (2012)
    901: City Lights (1931)
    693134: 'Dune: Part Two (2024)'
    28: Apocalypse Now (1979)
    77: Memento (2000)
    10681: WALL·E (2008)
    85: Raiders of the Lost Ark (1981)
    582: The Lives of Others (2006)
    299536: 'Avengers: Infinity War (2018)'
    599: Sunset Boulevard (1950)
    324857: 'Spider-Man: Into the Spider-Verse (2018)'
    975: Paths of Glory (1957)
    37257: Witness for the Prosecution (1957)
    694: The Shining (1980)
    914: The Great Dictator (1940)
    1163258: 12th Fail (2023)
    679: Aliens (1986)
    16869: Inglourious Basterds (2009)
    49026: The Dark Knight Rises (2012)
    354912: Coco (2017)
    279: Amadeus (1984)
    299534: 'Avengers: Endgame (2019)'
    670: Oldboy (2003)
    935: 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)'
    489: Good Will Hunting (1997)
    14: American Beauty (1999)
    197: Braveheart (1995)
    387: Das Boot (1981)
    128: Princess Mononoke (1997)
    372058: Your Name. (2016)
    12493: High and Low (1963)
    20453: 3 Idiots (2009)
    475557: Joker (2019)
    311: Once Upon a Time in America (1984)
    517814: Capernaum (2018)
    872: Singin' in the Rain (1952)
    25237: Come and See (1985)
    641: Requiem for a Dream (2000)
    1892: Return of the Jedi (1983)
    103663: The Hunt (2012)
    38: Eternal Sunshine of the Spotless Mind (2004)
    3782: Ikiru (1952)
    62: '2001: A Space Odyssey (1968)'
    500: Reservoir Dogs (1992)
    284: The Apartment (1960)
    947: Lawrence of Arabia (1962)
    46738: Incendies (2010)
    111: Scarface (1983)
    996: Double Indemnity (1944)
    213: North by Northwest (1959)
    949: Heat (1995)
    15: Citizen Kane (1941)
    832: M (1931)
    14160: Up (2009)
    600: Full Metal Jacket (1987)
    426: Vertigo (1958)
    194: Amélie (2001)
    872585: Oppenheimer (2023)
    185: A Clockwork Orange (1971)
    595: To Kill a Mockingbird (1962)
    60243: A Separation (2011)
    562: Die Hard (1988)
    9277: The Sting (1973)
    7508: Like Stars on Earth (2007)
    89: Indiana Jones and the Last Crusade (1989)
    19: Metropolis (1927)
    107: Snatch (2000)
    530915: 1917 (2019)
    2118: L.A. Confidential (1997)
    5156: Bicycle Thieves (1948)
    613: Downfall (2004)
    360814: Dangal (2016)
    1000837: I'm Still Here (2024)
    103: Taxi Driver (1976)
    556574: Hamilton (2020)
    106646: The Wolf of Wall Street (2013)
    272: Batman Begins (2005)
    490132: Green Book (2018)
    938: For a Few Dollars More (1965)
    239: Some Like It Hot (1959)
    37165: The Truman Show (1998)
    821: Judgment at Nuremberg (1961)
    10098: The Kid (1921)
    600354: The Father (2020)
    11324: Shutter Island (2010)
    705: All About Eve (1950)
    7345: There Will Be Blood (2007)
    329: Jurassic Park (1993)
    524: Casino (1995)
    745: The Sixth Sense (1999)
    11645: Ran (1985)
    361743: 'Top Gun: Maverick (2022)'
    6977: No Country for Old Men (2007)
    1091: The Thing (1982)
    1417: Pan's Labyrinth (2006)
    33: Unforgiven (1992)
    453: A Beautiful Mind (2001)
    24: 'Kill Bill: Vol. 1 (2003)'
    3090: The Treasure of the Sierra Madre (1948)
    11878: Yojimbo (1961)
    146233: Prisoners (2013)
    5925: The Great Escape (1963)
    762: Monty Python and the Holy Grail (1975)
    4935: Howl's Moving Castle (2004)
    1955: The Elephant Man (1980)
    521: Dial M for Murder (1954)
    548: Rashomon (1950)
    770: Gone with the Wind (1939)
    829: Chinatown (1974)
    25376: The Secret in Their Eyes (2009)
    508965: Klaus (2019)
    100: Lock, Stock and Two Smoking Barrels (1998)
    752: V for Vendetta (2006)
    150540: Inside Out (2015)
    359940: Three Billboards Outside Ebbing, Missouri (2017)
    627: Trainspotting (1996)
    826: The Bridge on the River Kwai (1957)
    1578: Raging Bull (1980)
    640: Catch Me If You Can (2002)
    275: Fargo (1996)
    59440: Warrior (2011)
    12445: 'Harry Potter and the Deathly Hallows: Part 2 (2011)'
    13223: Gran Torino (2008)
    70: Million Dollar Baby (2004)
    634649: 'Spider-Man: No Way Home (2021)'
    8392: My Neighbor Totoro (1988)
    76341: 'Mad Max: Fury Road (2015)'
    665: Ben-Hur (1959)
    21334: Children of Heaven (1997)
    3175: Barry Lyndon (1975)
    76203: 12 Years a Slave (2013)
    76: Before Sunrise (1995)
    78: Blade Runner (1982)
    120467: The Grand Budapest Hotel (2014)
    207: Dead Poets Society (1989)
    324786: Hacksaw Ridge (2016)
    210577: Gone Girl (2014)
    11423: Memories of Murder (2003)
    7984: In the Name of the Father (1993)
    2062: Ratatouille (2007)
    962: The Gold Rush (1925)
    265195: Wild Tales (2014)
    10191: How to Train Your Dragon (2010)
    992: Sherlock Jr. (1924)
    578: Jaws (1975)
    11778: The Deer Hunter (1978)
    961: The General (1926)
    24238: Mary and Max (2009)
    359724: Ford v Ferrari (2019)
    204: The Wages of Fear (1953)
    654: On the Waterfront (1954)
    3083: Mr. Smith Goes to Washington (1939)
    614: Wild Strawberries (1957)
    1118224: Maharaja (2024)
    1092: The Third Man (1949)
    263115: Logan (2017)
    1366: Rocky (1976)
    18148: Tokyo Story (1953)
    115: The Big Lebowski (1998)
    314365: Spotlight (2015)
    490: The Seventh Seal (1957)
    218: The Terminator (1984)
    264644: Room (2015)
    895006: 'Demon Slayer: Kimetsu no Yaiba - Tsuzumi Mansion Arc (2022)'
    22: 'Pirates of the Caribbean: The Curse of the Black Pearl (2003)'
    205: Hotel Rwanda (2004)
    792: Platoon (1986)
    855400: Jai Bhim (2021)
    406: La Haine (1995)
    80: Before Sunset (2004)
    887: The Best Years of Our Lives (1946)
    780: The Passion of Joan of Arc (1928)
    9552: The Exorcist (1973)
    630: The Wizard of Oz (1939)
    96721: Rush (2013)
    15121: The Sound of Music (1965)
    28178: "Hachi: A Dog's Tale (2009)"
    235: Stand by Me (1986)
    10774: Network (1976)
    13393: My Father and My Son (2005)
    290098: The Handmaiden (2016)
    10386: The Iron Giant (1999)
    198: To Be or Not to Be (1942)
    17295: The Battle of Algiers (1966)
    5915: Into the Wild (2007)
    596: The Grapes of Wrath (1940)
    137: Groundhog Day (1993)
    50014: The Help (2011)
    378064: 'A Silent Voice: The Movie (2016)'
    55: Amores Perros (2000)
    223: Rebecca (1940)
    15244: A Man Escaped (1956)
IMDb Lowest Rated:
  Movies Missing (TMDb IDs):
    13805: Disaster Movie (2008)
    22293: 'Manos: The Hands of Fate (1966)'
    40016: 'Birdemic: Shock and Terror (2010)'
    31117: 'Superbabies: Baby Geniuses 2 (2004)'
    295884: Saving Christmas (2014)
    63315: The Hottie & The Nottie (2008)
    11059: House of the Dead (2003)
    10214: Son of the Mask (2005)
    679844: Radhe (2021)
    9760: Epic Movie (2007)
    19213: Pledge This! (2006)
    5491: Battlefield Earth (2000)
    12142: Alone in the Dark (2005)
    14164: Dragonball Evolution (2009)
    496320: Race 3 (2018)
    116977: Foodfight! (2012)
    19157: Going Overboard (1989)
    31246: From Justin to Kelly (2003)
    31279: Turks in Space (2006)
    7278: Meet the Spartans (2008)
    8046: Gigli (2003)
    9596: Daniel, the Wizard (2004)
    10073: Date Movie (2006)
    536869: Cats (2019)
    22345: Baby Geniuses (1999)
    10696: Glitter (2001)
    94365: The Human Centipede 3 (Final Sequence) (2015)
    681887: Cosmic Sin (2021)
    717728: 'Jeepers Creepers: Reborn (2022)'
    829557: '365 Days: This Day (2022)'
    580: 'Jaws: The Revenge (1987)'
    734253: Adipurush (2023)
    980078: 'Winnie the Pooh: Blood and Honey (2023)'
    876671: The Cost of Deception (2021)
    168705: BloodRayne (2005)
    31245: Hobgoblins (1988)
    26914: Troll 2 (1990)
    495339: 'Enes Batur: Imagination or Reality? (2018)'
    218043: Left Behind (2014)
    664413: 365 Days (2020)
    15581: Who's Your Caddy? (2007)
    71880: Jack and Jill (2011)
    11535: Rollerball (2002)
    32307: Santa Claus Conquers the Martians (1964)
    439015: Slender Man (2018)
    503129: Student of the Year 2 (2019)
    314: Catwoman (2004)
    11511: Kazaam (1996)
    590706: Jiu Jitsu (2020)
    651571: Breach (2020)
    603673: Laxmii (2020)
    8854: Steel (1997)
    485774: The Open House (2018)
    225703: The Starving Games (2013)
    40264: Vampires Suck (2010)
    378236: The Emoji Movie (2017)
    415861: Smolensk (2016)
    10152: 'Dumb and Dumberer: When Harry Met Lloyd (2003)'
    250551: Gunday (2014)
    16780: The Return of the Texas Chainsaw Massacre (1995)
    4258: Scary Movie 5 (2013)
    46040: Tees Maar Khan (2010)
    594669: Baaghi 3 (2020)
    17473: The Room (2003)
    13908: The Master of Disguise (2002)
    7916: Far Cry (2008)
    829560: The Next 365 Days (2022)
    14144: Daddy Day Camp (2007)
    5227: Hercules in New York (1970)
    11546: 'Police Academy: Mission to Moscow (1994)'
    14123: Bratz (2007)
    9823: 'Mortal Kombat: Annihilation (1997)'
    9544: FearDotCom (2002)
    32302: '3 Ninjas: High Noon at Mega Mountain (1998)'
    11867: Barb Wire (1996)
    787163: Liger (2022)
    13995: Captain America (1990)
    351819: Fifty Shades of Black (2016)
    56288: 'Spy Kids: All the Time in the World (2011)'
    27793: The NeverEnding Story III (1994)
    415: Batman & Robin (1997)
    551808: Black Christmas (2019)
    19139: 'Goal III: Taking on the World (2009)'
    17692: Jaws 3-D (1983)
    10253: 'Dragon Wars: D-War (2007)'
    11411: 'Superman IV: The Quest for Peace (1987)'
    11849: Dungeons & Dragons (2000)
    20196: Mac and Me (1988)
    67911: 'Bucky Larson: Born to Be a Star (2011)'
    791: The Fog (2005)
    9708: The Wicker Man (2006)
    5857: I Know Who Killed Me (2007)
    71668: Piranha 3DD (2012)
    244688: The Hungover Games (2014)
    6116: Spice World (1997)
    12177: The Love Guru (2008)
    496339: Dabangg 3 (2019)
    2312: 'In the Name of the King: A Dungeon Siege Tale (2007)'
    14199: The Adventures of Sharkboy and Lavagirl (2005)
    74997: The Human Centipede 2 (Full Sequence) (2011)
