IMDb Top 250:
  Movies Missing (TMDb IDs):
    389: 12 Angry Men (1957)
    424: Schindler's List (1993)
    122: 'The Lord of the Rings: The Return of the King (2003)'
    120: 'The Lord of the Rings: The Fellowship of the Ring (2001)'
    429: The Good, the Bad and the Ugly (1966)
    121: 'The Lord of the Rings: The Two Towers (2002)'
    510: One Flew Over the Cuckoo's Nest (1975)
    1585: It's a Wonderful Life (1946)
    346: Seven Samurai (1954)
    598: City of God (2002)
    637: Life Is Beautiful (1997)
    129: Spirited Away (2001)
    423: The Pianist (2002)
    539: Psycho (1960)
    98: Gladiator (2000)
    8587: The Lion King (1994)
    244786: Whiplash (2014)
    12477: Grave of the Fireflies (1988)
    14537: Harakiri (1962)
    289: Casablanca (1943)
    77338: The Intouchables (2011)
    11216: Cinema Paradiso (1988)
    3082: Modern Times (1936)
    567: Rear Window (1954)
    335: Once Upon a Time in the West (1968)
    901: City Lights (1931)
    1163258: 12th Fail (2023)
    10681: WALL·E (2008)
    582: The Lives of Others (2006)
    599: Sunset Boulevard (1950)
    324857: 'Spider-Man: Into the Spider-Verse (2018)'
    37257: Witness for the Prosecution (1957)
    914: The Great Dictator (1940)
    354912: Coco (2017)
    670: Oldboy (2003)
    279: Amadeus (1984)
    387: Das Boot (1981)
    197: Braveheart (1995)
    128: Princess Mononoke (1997)
    372058: Your Name. (2016)
    12493: High and Low (1963)
    311: Once Upon a Time in America (1984)
    20453: 3 Idiots (2009)
    872: Singin' in the Rain (1952)
    517814: Capernaum (2018)
    25237: Come and See (1985)
    641: Requiem for a Dream (2000)
    103663: The Hunt (2012)
    3782: Ikiru (1952)
    947: Lawrence of Arabia (1962)
    284: The Apartment (1960)
    46738: Incendies (2010)
    213: North by Northwest (1959)
    832: M (1931)
    996: Double Indemnity (1944)
    426: Vertigo (1958)
    194: Amélie (2001)
    14160: Up (2009)
    595: To Kill a Mockingbird (1962)
    60243: A Separation (2011)
    9277: The Sting (1973)
    7508: Like Stars on Earth (2007)
    19: Metropolis (1927)
    556574: Hamilton (2020)
    2118: L.A. Confidential (1997)
    5156: Bicycle Thieves (1948)
    613: Downfall (2004)
    360814: Dangal (2016)
    938: For a Few Dollars More (1965)
    239: Some Like It Hot (1959)
    490132: Green Book (2018)
    10098: The Kid (1921)
    600354: The Father (2020)
    821: Judgment at Nuremberg (1961)
    705: All About Eve (1950)
    524: Casino (1995)
    11645: Ran (1985)
    1417: Pan's Labyrinth (2006)
    6977: No Country for Old Men (2007)
    1091: The Thing (1982)
    24: 'Kill Bill: Vol. 1 (2003)'
    3090: The Treasure of the Sierra Madre (1948)
    11878: Yojimbo (1961)
    5925: The Great Escape (1963)
    548: Rashomon (1950)
    4935: Howl's Moving Castle (2004)
    1955: The Elephant Man (1980)
    829: Chinatown (1974)
    521: Dial M for Murder (1954)
    770: Gone with the Wind (1939)
    752: V for Vendetta (2006)
    100: Lock, Stock and Two Smoking Barrels (1998)
    25376: The Secret in Their Eyes (2009)
    150540: Inside Out (2015)
    826: The Bridge on the River Kwai (1957)
    508965: Klaus (2019)
    634649: 'Spider-Man: No Way Home (2021)'
    640: Catch Me If You Can (2002)
    59440: Warrior (2011)
    13223: Gran Torino (2008)
    8392: My Neighbor Totoro (1988)
    70: Million Dollar Baby (2004)
    12445: 'Harry Potter and the Deathly Hallows: Part 2 (2011)'
    21334: Children of Heaven (1997)
    665: Ben-Hur (1959)
    76: Before Sunrise (1995)
    962: The Gold Rush (1925)
    11423: Memories of Murder (2003)
    7984: In the Name of the Father (1993)
    265195: Wild Tales (2014)
    11778: The Deer Hunter (1978)
    961: The General (1926)
    654: On the Waterfront (1954)
    992: Sherlock Jr. (1924)
    10191: How to Train Your Dragon (2010)
    1092: The Third Man (1949)
    204: The Wages of Fear (1953)
    24238: Mary and Max (2009)
    614: Wild Strawberries (1957)
    3083: Mr. Smith Goes to Washington (1939)
    2062: Ratatouille (2007)
    18148: Tokyo Story (1953)
    264644: Room (2015)
    490: The Seventh Seal (1957)
    263115: Logan (2017)
    205: Hotel Rwanda (2004)
    780: The Passion of Joan of Arc (1928)
    406: La Haine (1995)
    80: Before Sunset (2004)
    887: The Best Years of Our Lives (1946)
    9552: The Exorcist (1973)
    855400: Jai Bhim (2021)
    10774: Network (1976)
    28178: "Hachi: A Dog's Tale (2009)"
    13393: My Father and My Son (2005)
    290098: The Handmaiden (2016)
    15121: The Sound of Music (1965)
    198: To Be or Not to Be (1942)
    17295: The Battle of Algiers (1966)
    596: The Grapes of Wrath (1940)
    55: Amores Perros (2000)
    223: Rebecca (1940)
    10386: The Iron Giant (1999)
    50014: The Help (2011)
    3078: It Happened One Night (1934)
    352173: Drishyam (2015)
    812: Aladdin (1992)
    117691: Gangs of Wasseypur - Part 1 (2012)
IMDb Lowest Rated:
  Movies Missing (TMDb IDs):
    13805: Disaster Movie (2008)
    22293: 'Manos: The Hands of Fate (1966)'
    40016: 'Birdemic: Shock and Terror (2010)'
    31117: 'Superbabies: Baby Geniuses 2 (2004)'
    295884: Saving Christmas (2014)
    63315: The Hottie & The Nottie (2008)
    11059: House of the Dead (2003)
    10214: Son of the Mask (2005)
    9760: Epic Movie (2007)
    679844: Radhe (2021)
    19213: Pledge This! (2006)
    5491: Battlefield Earth (2000)
    12142: Alone in the Dark (2005)
    14164: Dragonball Evolution (2009)
    496320: Race 3 (2018)
    116977: Foodfight! (2012)
    31246: From Justin to Kelly (2003)
    31279: Turks in Space (2006)
    7278: Meet the Spartans (2008)
    8046: Gigli (2003)
    10073: Date Movie (2006)
    9596: Daniel, the Wizard (2004)
    536869: Cats (2019)
    22345: Baby Geniuses (1999)
    10696: Glitter (2001)
    94365: The Human Centipede 3 (Final Sequence) (2015)
    681887: Cosmic Sin (2021)
    717728: 'Jeepers Creepers: Reborn (2022)'
    829557: '365 Days: This Day (2022)'
    26914: Troll 2 (1990)
    168705: BloodRayne (2005)
    31245: Hobgoblins (1988)
    876671: The Cost of Deception (2021)
    980078: 'Winnie the Pooh: Blood and Honey (2023)'
    734253: Adipurush (2023)
    495339: 'Enes Batur: Imagination or Reality? (2018)'
    664413: 365 Days (2020)
    15581: Who's Your Caddy? (2007)
    11535: Rollerball (2002)
    32307: Santa Claus Conquers the Martians (1964)
    439015: Slender Man (2018)
    11511: Kazaam (1996)
    503129: Student of the Year 2 (2019)
    651571: Breach (2020)
    8854: Steel (1997)
    603673: Laxmii (2020)
    485774: The Open House (2018)
    40264: Vampires Suck (2010)
    225703: The Starving Games (2013)
    378236: The Emoji Movie (2017)
    46040: Tees Maar Khan (2010)
    10152: 'Dumb and Dumberer: When Harry Met Lloyd (2003)'
    4258: Scary Movie 5 (2013)
    16780: The Return of the Texas Chainsaw Massacre (1995)
    250551: Gunday (2014)
    13908: The Master of Disguise (2002)
    415861: Smolensk (2016)
    14144: Daddy Day Camp (2007)
    11546: 'Police Academy: Mission to Moscow (1994)'
    14123: Bratz (2007)
    5227: Hercules in New York (1970)
    7916: Far Cry (2008)
    594669: Baaghi 3 (2020)
    9823: 'Mortal Kombat: Annihilation (1997)'
    9544: FearDotCom (2002)
    11867: Barb Wire (1996)
    32302: '3 Ninjas: High Noon at Mega Mountain (1998)'
    351819: Fifty Shades of Black (2016)
    13995: Captain America (1990)
    56288: 'Spy Kids: All the Time in the World (2011)'
    551808: Black Christmas (2019)
    19139: 'Goal III: Taking on the World (2009)'
    11849: Dungeons & Dragons (2000)
    10253: 'Dragon Wars: D-War (2007)'
    20196: Mac and Me (1988)
    67911: 'Bucky Larson: Born to Be a Star (2011)'
    791: The Fog (2005)
    6116: Spice World (1997)
    71668: Piranha 3DD (2012)
    5857: I Know Who Killed Me (2007)
    787163: Liger (2022)
    244688: The Hungover Games (2014)
    14199: The Adventures of Sharkboy and Lavagirl (2005)
    12177: The Love Guru (2008)
    2312: 'In the Name of the King: A Dungeon Siege Tale (2007)'
    74997: The Human Centipede 2 (Full Sequence) (2011)
    889: The Flintstones in Viva Rock Vegas (2000)
