name: Docker Latest Release

on:
  push:
    branches: [ master ]

jobs:

  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - tag: latest
            file: Dockerfile
          - tag: lxml-latest
            file: Dockerfile.lxml
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./${{ matrix.node.file }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: kometateam/kometa:${{ matrix.node.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Discord Success Notification
        uses: Kometa-Team/discord-notifications@master
        if: success()
        with:
          webhook_id_token: ${{ secrets.BUILD_WEBHOOK }}
          title: "${{ vars.REPO_NAME }} ${{ matrix.node.tag }}: **Build Successful**"
          url: https://github.com/Kometa-Team/${{ vars.REPO_NAME }}/actions/runs/${{ github.run_id }}
          color: 844716
          username: Kobota
          avatar_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/master/.github/bot.png
          author: Docker
          author_icon_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/master/.github/docker.png

      - name: Discord Failure Notification
        uses: Kometa-Team/discord-notifications@master
        if: failure()
        with:
          webhook_id_token: ${{ secrets.BUILD_WEBHOOK }}
          message: <@&1079153184007790652>
          title: "${{ vars.REPO_NAME }} ${{ matrix.node.tag }}: **Build Failed**"
          url: https://github.com/Kometa-Team/${{ vars.REPO_NAME }}/actions/runs/${{ github.run_id }}
          color: 14879811
          username: Kobota
          avatar_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/master/.github/bot.png
          author: Docker
          author_icon_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/master/.github/docker.png