name: Release

on:
  release:
    types: [ published ]

jobs:

  release-notification:

    runs-on: ubuntu-latest
    steps:

      - name: Send Discord Release Notification
        uses: Kometa-Team/discord-notifications@master
        with:
          webhook_id_token: ${{ secrets.RELEASE_WEBHOOK }}
          release: true
          title: Release VERSION
          message: "<@&967002324646113290> - A new version of Kometa has been released and is available to all users.\n\nWe **strongly** recommend users who previously switched to the `nightly` or `develop` branches to resolve any previous issues to now switch back to the `latest` branch now."
          username: Kobota
          avatar_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/develop/.github/bot.png
          author: Kometa Release
          author_icon_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/develop/.github/release.png